// This file is auto-generated by the build system.
export const PACKAGE_NAME: string = "html-living-framework";
export const PACKAGE_VERSION: string = "1.0.0";
export const GIT_BRANCH: string | undefined = "main";
export const GIT_COMMIT: string | undefined = "b23e3bcc16ad8da996acffcded0cfc207aaf3f53";
