"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GIT_COMMIT = exports.GIT_BRANCH = exports.PACKAGE_VERSION = exports.PACKAGE_NAME = void 0;
// This file is auto-generated by the build system.
exports.PACKAGE_NAME = "html-living-framework";
exports.PACKAGE_VERSION = "1.0.0";
exports.GIT_BRANCH = "main";
exports.GIT_COMMIT = "b23e3bcc16ad8da996acffcded0cfc207aaf3f53";
//# sourceMappingURL=version.js.map